### ISSUE TITLE
Fritzbox rejects password after getting data two times

### ISSUE THREAD

**Issue by deltaphi** [bb-Ricardo/fritzinfluxdb#56]
Since I got Grafana to work in #54, I have now been running fritzinfluxdb for a short while. However, I found that for every time I start the fritzinfluxdb container, there are only two data points received, spaced about two minutes apart. After that, there is no more data. I'm currently running next-release as of yesterday evening.

Manually checking the logs in the FritzBox reveals many entries like the following:

```
2022-09-21 22:00:04
System
Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse REDACTED gescheitert (falsches Kennwort).
2022-09-21 21:55:05
System
Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse REDACTED gescheitert (falsches Kennwort).
2022-09-21 21:50:12
System
Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse REDACTED gescheitert (falsches Kennwort). [3 Meldungen seit 21.09.22 21:50:04]
2022-09-21 21:49:34
System
Anmeldung des Benutzers fritzinfluxdb an der FRITZ!Box-Benutzeroberfläche von IP-Adresse REDACTE. [4 Meldungen seit 21.09.22 21:47:24]
```

I use a dedicated user account for fritzinfluxdb. The REDACTED IP adress is the address of the machine fritzinfluxdb is running on - and nothing else is logging in from that machine. Given that neither the FrotzBox nor fritzinfluxdb suddenly change the password they are using, this would seem to be some kind of rate limiting for logins of a particular user. However, I'm not aware of such a feature on FritzBoxes, and this does not seem to be a problem for others, so I'm kind of stumped as to the actual cause of the problem here.

What can I do to make fritzinfluxdb get data continuously and reliably?

**Comment by deltaphi** [comment]
Things are strange. While trying to pull logs from docker I somehow managed to blow up my entire setup and it took me until just a moment ago to get all the pieces put back together.

In the meantime, fritzinfluxdb has been up since yesterday evening and now I can see in Grafana that there is a much higher density of data points - so much in fact, that you couldn't tell from the graphs alone that fritzinfluxdb still fails every once in a while, as the Fritz! logs still inform me.

So what I am observing in a bit more detail: When I start or restart fritzinfluxdb, the Fritz!Box Log reports that the respective user logged in successfully - and reports so repeatedly, I'm seeing 3-6 times. About 2-5 minutes later, there is another log entry, stating that a login from the same IP (so that must be fritzinfluxdb) failed - and I will be getting that message every 5 minutes, basically indefinitely. See the screenshot for an example taken from Grafana - these messages continue until the next time I restart the container:

![grafik](https://user-images.githubusercontent.com/2348915/192023832-42be2fc5-c397-4e94-8907-81ec5acd18a6.png)

Also, *this* time around I'm still seeing data for e.g. uplink and downlink speeds for the entire day that I'm getting login failure messages. This was not the case before - the graphs in Grafana just stopped, which tipped me off to this problem.

I did manage to pull the logs from docker, but that's currently 55k lines. I can't seem to find anything but the Error Logs pulled from the Fritz!Box on there and I'd rather not post the full log with quite a bit of private information publicly. Can you tell me what the error string for a failed login would be, so that I can narrow down the section of the log a little bit?

**Comment by bb-Ricardo** [comment]
I currently investigating an issue with telephone logs. They can be older then the retention period and InfluxDB refuses to write data if it includes measurements older then said retention period. Will let you know when I have solved this issue.

**Comment by bb-Ricardo** [comment]
I just pushed a change to `next-release` to mitigate the issue with data older then the retention period. Maybe you can give this a go.

**Comment by deltaphi** [comment]
I habe been running 15aff852 for a bit over a day now. I’m still seeing the log messages about login failures in the Fritz!Box, but data collection for at least the DSL parameters and the logs themselves did work without problems so far.

**Comment by bb-Ricardo** [comment]
This is soo strange. How is there one connection working and now and then the other complaining? Did you see anything odd in the logs, or are they just to overwhelming?

Would you mind sending them to my email? You can find the address near the top of fritzinfluxdb.py

Thank you.

**Comment by deltaphi** [comment]
@bb-Ricardo Apologies for not getting back to on this you sooner, I was occupied with non-computer related issues. I have pulled alog from docker for about the last two hours and wanted to E-Mail it to you - but it turns out there is no E-Mail in fritzinfluxdb.py - or, in fact, in any file in the repository.

**Comment by bb-Ricardo** [comment]
Hi,

Yes you are correct 😬. Wishful thinking. Usually put it in there but forgot it in this project. Please use this one: https://github.com/bb-Ricardo/icinga-slack-bot/blob/ff67792c6439a5c94b66daaa23ba00371a21ee51/icinga-bot.py#L36

**Comment by deltaphi** [comment]
Thanks. I just sent the E-Mail.

**Comment by bb-Ricardo** [comment]
thank you

**Comment by deltaphi** [comment]
After some debugging via E-Mail: This appears to be some kind of fluke related to my system, as the errors occur even when I stop my fritzinfluxdb container. I have not found a solution, but it does not seem to be related to the fritzinfluxdb software itself.
