### ISSUE TITLE
Duplicated log messages in FritzOS 7.39 BETA

### ISSUE THREAD

**Issue by m-arndt** [bb-Ricardo/fritzinfluxdb#58]
Using fritzinfluxdb with FritzOS 7.39 duplicates every log message into all five log categories 

![Screenshot duplicated log messages](https://user-images.githubusercontent.com/15635134/193427868-2799862f-59c9-4800-8244-ea0193b407bd.png)

**Comment by m-arndt** [comment]
I did some digging and I think the `filter`-Option sent to `data.lua` does no longer work on 7.39.

**Comment by bb-Ricardo** [comment]
Hi, yes this was my idea as well. Can you use the browser dev tools to figure out which params need to be set for the different log types?

**Comment by m-arndt** [comment]
Hi, the new filter values are `sys`, `net`, `fon`, `wlan` and `usb`. Didn't even occur to me to look in the dev tools.

**Comment by m-arndt** [comment]
Sorry should have included that in my message. These are all the values that are sent:
```
xhr=1
sid=<redacted>
lang=de
page=log
xhrId=log
filter=sys
useajax=1
no_sidrenew=
```
I just tested the new filter-values and they are working without adding the other parameters

**Comment by bb-Ricardo** [comment]
great, thank you. Will change it in the source.

**Comment by bb-Ricardo** [comment]
should be fixed in current `next-release` branch. Maybe you can test this version.

**Comment by kine90** [comment]
Hello everyone, thanks a lot for this great tool, which is helping me a lot to investigate a problem which my box restarting itself very often.
I'd like to know if I am the only one still getting some duplicate log entries. I am using Influx2, Fritz!Box 7530AX and Fritz!OS 7.31. Only some lines appears double.
![Screenshot_2023-03-22_16-46-57](https://user-images.githubusercontent.com/73344196/226963017-cadf8693-0c3a-4036-9a4c-5d44ebfdedbb.jpg)
